language: python
cache: pip
python:
- 3.9
install:
- pip install -r requirements/dev.txt
before_script:
- export APP_SECRET="test_secret"
- export FLASK_ENV=test
script:
- pytest
deploy:
  provider: heroku
  app: topicdiff
  api_key:
    secure: WeC8Z21P/FtpKfBe5LWjqEx4UiKi9GQ+WS+IlX2UMECw0lnbweJ/Zj5kEKbE1NhubLAIfsz746edw0bKzy4fUncLGtPtppbaxHygU9V70o9kgpQgGRe1Nx02hA+nIyhoBV2Y80HBWHfvXi6xuDSd+yTvGn7FxLYkjWC7dCvKJ6mH0edanqn8UWTDj5VwAJjUSyJ10pauvukZTlHZXixOHH0kdwTmxVjI+7GaByviyEhVhRjwaiybRFQTnT6H6TOQ2lWMJvvt5iYtHDXZ3zx3OAlC7JPFhns0rP+pQWWL2eNVbsjrpopy+SHMEdL6aDhPB6N9LzgBQu0dVn8l5amwnvNLE07br9Una5NXBw7OmQlqaTA7LxMEhATTh1DrXKTxav1r+uhE35wx4XifTG68Vz/ZyvauU44rJBE9Bj2a/b3QDIfUTDw5eqiJY3KW55BlvEpz18AsSg1dVAZerkDqkzh0SNWpzoG397IXWhVHFQaoH2QjpoM85keEOZO6PE7cS9IuXOS1enAFrS42gLRufTUSQwI5N0h4Hfvgv5aaM+HeYA+Ji2ra9O5xYVzH6pV1N4yyCJ809Z7NsypXlor0wakBJk2Uz6dKJ1EbB5bXjHJN+vnaBsKAqfufqHyK4QTrtiRfjtH382C86AwWE8Mv20eY9LiRns2tjoCYuATzVQk=
  on: master
